### PR TITLE
Custom Celestial Types are now supported.

### PR DESCRIPTION
**Pull request by Codetoil**
I need feedback.

### CODE REVIEW

**Comment by ROMVoid95** [comment]
I don't understand why these changes are made. Any type that an addon creates is supported through inheritance, as long as they extend `CelestialBody` or their superclass extends `CelestialBody`.

And the changes made will bring breaking changes to existing addons.

**Comment by Codetoil** [comment]
From your comment on https://github.com/TeamGalacticraft/Galacticraft-Legacy/pull/84#issuecomment-1221361672;
> However, I have been wanting to add the capability to register custom celestial types directly to the GC Registry instead of only being constrained to extending the current types GC defines. Since this would also be a feature that would benefit what your wanting to do here. and would be willing to implement this, I would be more than happy to further review a PR for that.

This was my intention.

**Comment by ROMVoid95** [comment]
Understood, however the changes still do not extend what the changes already made to the registry do (the last check if `object instanceof CelestialBody`)

**Comment by Codetoil** [comment]
What do you mean?

**Pull request closed without merging**
